### ISSUE TITLE
Use the closest package.json / yarn.lock

### ISSUE THREAD

**Issue by borekb** [gamunu/vscode-yarn#1]
I have a VSCode project with multiple packages and this extension doesn't seem to recognize it, I get this error:

> Cannot read 'package.json'

I guess it's because there is no `package.json` in workspace root.

The ideal behavior for me is:

- When I have `package.json` opened as an active editor, `yarn` should be invoked on it (or on the related `yarn.lock` to be precise).
- When I have a focus on some folder in the sidebar, and that folder contains `yarn.lock` / `package.json`, that should be used as the context.

**Comment by gamunu** [comment]
yes, it seems like a good idea. I'll try to implement in the next release.

**Comment by gamunu** [comment]
I think the second behavior is cannot be implemented because of the vscode API simply doesn't support it Microsoft/vscode#15991. feel free to submit a pull request if you have a workaround for it. :smiley:

What I planned is,
1. If a package.json is opened as an active editor `yarn` will be invoked on it.
2. If no package.json is opened as an active editor then it will use focused folder to invoke yarn (Microsoft/vscode#15991).
3. If the above scenarios fail to satisfy fallback to `package.json` in project root folder.

**Comment by pjmagee** [comment]
Yes please! My root directory has multiple projects that are part of a solution so being able to either configure yarn package.json location or currently active open package.json can be used for yarn install would be great.

**Comment by gamunu** [comment]
@borekb @pjmagee Done,
01. If a package.json is opened as an active editor/focused tab yarn will be invoked on it.
02. :eyes:
03. If the above scenario fails to satisfy extension will fallback to package.json in project root folder.

**Comment by kunalgolani** [comment]
I have my `package.json` in a sub-folder of the project root - can it be a configuration option to specify the path to it so that I can run a script from anywhere without having to open my `package.json` file?

**Comment by gamunu** [comment]
Possible. what do you think about the below flow of execution,

1.If a package.json is opened as an active editor/focused tab yarn will be invoked on it.
2.If the package.json is explicitly defined in the configuration yarn will invoke on it.
3.If above scenarios fail to satisfy. The extension will fall back to package.json in project root folder.

**Comment by kunalgolani** [comment]
@gamunu sounds good to me!

**Comment by gamunu** [comment]
Closing this. The new feature context menu introduced in [**v1.5.0**](https://github.com/gamunu/vscode-yarn/releases/tag/v1.5.0) will provide much better integration.
