### ISSUE TITLE
yarn.runInTerminal set true by default

### ISSUE THREAD

**Issue by NN---** [gamunu/vscode-yarn#11]
I think it is good idea to have yarn.runInTerminal set to true by default like npm.runInTerminal does.
( https://marketplace.visualstudio.com/items?itemName=eg2.vscode-npm-script )

**Comment by osya** [comment]
The cons of setting `"yarn.runInTerminal": true` is launching the command `Yarn: Terminate Running Yarn Script` produces `Killing is only supported when the setting "runInTerminal" is "false"`

**Comment by gamunu** [comment]
Yes. right now, there's no way to capture child-process when runInTerminal.
