### ISSUE TITLE
Test command does not seem to be doin anything

### ISSUE THREAD

**Issue by burtek** [gamunu/vscode-yarn#13]
## Expected Behavior
Running command `yarn-script.test` should open a terminal (or at least output) window with test results

## Actual Behavior
Nothing happens

## Steps to Reproduce the Problem

Run `yarn-script.test` on a project with test command properly setup in `package.json` (running `yarn test` in terminal works)

## Specifications

Platform: windows 10 x64

![image](https://user-images.githubusercontent.com/2940958/47193445-39c8b000-d353-11e8-909f-e1dfffe510d9.png)

**Comment by burtek** [comment]
Just additional info:

package.json:
```json
{
    "scripts": {
        "test": "jest"
    }
}
```

User settings:
```json
{
    "yarn.runInTerminal": true,
    "yarn.dontHideOutputOnSuccess": true
}
```

**Comment by gamunu** [comment]
<img width="614" alt="Screen Shot 2019-12-07 at 11 26 07 PM" src="https://user-images.githubusercontent.com/4501687/70378653-f9f2cc80-1948-11ea-852a-381a1450ae7c.png">


This is working, make sure you have no other opened `package.json` if the project is a multi-root project.
