### ISSUE TITLE
Suggestion: Find scripts in multiple `package.json` files

### ISSUE THREAD

**Issue by FokkeZB** [gamunu/vscode-yarn#15]
## Expected Behavior

I work in a monorepo and would like to be able to run scripts form any of the `package.json` files. Well, not the ones under `node_modules` folders and perhaps there's some I'd like to black or whitelist. Perhaps `yarn.packageJson` could accept an array?

## Actual Behavior

Currently, it only uses the root `package.json`.

**Comment by gamunu** [comment]
@FokkeZB I'm working on a solution to specify an array.. in the meantime, you could right-click on any of the package JSON files and select `Install Packages` or highlight the file and issue the yarn install command it will automatically detect it.

**Comment by gamunu** [comment]
Multi root workspace support added in v2.0.0. It can be utilized in monorepos.
