### ISSUE TITLE
Installing the extension breaks Ctrl-r

### ISSUE THREAD

**Issue by fogzot** [gamunu/vscode-yarn#19]
## Expected Behavior

Installing the extension should not disabled default keyboard shortcuts.

## Actual Behavior

Installing the extension breaks the keyboard shortcut `Ctrl-r`.

## Steps to Reproduce the Problem

  1. Install the extension
  2. Try opening the file/project history using `Ctrl-r`
  3. It does not work (asks for a chord)

## Specifications

  - Version: VS Code 1.41.1, vscode-yarn 1.7.0
  - Platform: Linux

**Comment by mozgbrasil** [comment]
+1
