### ISSUE TITLE
yarn 不是内部或外部命令

### ISSUE THREAD

**Issue by xiaosunJessica** [gamunu/vscode-yarn#2]
在vs code中， yarn 不是内部或外部命令

**Comment by gamunu** [comment]
This extension depends on `yarn` binary. please follow Yarn installation guide.
[https://yarnpkg.com/lang/en/docs/install/](https://yarnpkg.com/lang/en/docs/install/)

**Comment by xiaosunJessica** [comment]
I have installed yarn, and on window commond, yarn is valid, but in vs code terminal， it's invalid

**Comment by gamunu** [comment]
Seems like a path issue. there is a workaround for this.

You can try adding following setting to VSCode
```
{
	"yarn.runInTerminal": true
}
```
or if it doen't work you can specify the yarn binary path, the extension will pick up the path you configured when executing commands
```
{
   yarn.bin: "path to yarn binary"
}
```

**Comment by xiaosunJessica** [comment]
![image](https://user-images.githubusercontent.com/17615820/27788254-7b1d25ca-601a-11e7-91c1-d6a05200de7c.png)
I have configure, but still not work

**Comment by gamunu** [comment]
it should be `c:\\program files(x86)\\\yarn\\bin\\yarn`

**Comment by xiaosunJessica** [comment]
yes, has resolved, thanks
