### ISSUE TITLE
Overwrites default vscode keyboard shortcuts

### ISSUE THREAD

**Issue by u-atharva** [gamunu/vscode-yarn#32]
## Expected Behavior
<kbd>Ctrl</kbd> + <kbd>r</kbd> should open `recents`

## Actual Behavior
![image](https://user-images.githubusercontent.com/70993547/156966425-53f1801d-6f2e-4a47-bb6f-e2e9c0535826.png)

## Steps to Reproduce the Problem

  1. Install this extention
  2. Try using the keyboard shortcut combination

## Specifications

  - Version: [vscode-yarn](https://github.com/gamunu/vscode-yarn) v2.1.0
  - Platform: VSCode v1.65.0
  - OS: Windows 11

**Comment by gamunu** [comment]
@atharva-u-01 they keybindings only activate if the terminal is in focus.

**Comment by gamunu** [comment]
It is challenging to come up with free keybinding shortcuts, so the current approach is to defer this to the user. Apologies!
