### ISSUE TITLE
Configs aren't registered

### ISSUE THREAD

**Issue by Spown** [gamunu/vscode-yarn#7]
![](https://drive.google.com/uc?id=1m1zVrkSBbHIjabsBxZsTL_eilfb3qJ7M)
![](https://drive.google.com/uc?id=1GE6zkB2uQmcyl5ZP9_civKu8j6wjgOIX)

I guess it's because [you've put your ``configuration``](https://github.com/gamunu/vscode-yarn/blob/master/package.json#L103) templates directly into ``package.json`` root instead of making it a property of ``contributes``.

**Comment by gamunu** [comment]
Oh, that's some pretty serious bug.
