### ISSUE TITLE
 yarn.packageJson setting is non-functional

### ISSUE THREAD

**Issue by sashasklar** [gamunu/vscode-yarn#9]
## Expected Behavior
According to the extension description:
"yarn.packageJson default package json path. relative to current project root"

see: https://marketplace.visualstudio.com/items?itemName=gamunu.vscode-yarn

## Actual Behavior
yarn.packageJson is not available in the settings configuration
setting the property has no effect.

## Steps to Reproduce the Problem

  1. Install the plugin
  2. Open the workspace settings
  3. add the yarn.packageJson property. Note that it is not shown as available

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by hellboy81** [comment]
still does not work

**Comment by gamunu** [comment]
<img width="680" alt="Screen Shot 2019-12-07 at 10 10 48 PM" src="https://user-images.githubusercontent.com/4501687/70378428-47216f00-1946-11ea-936a-e4184a9f09a0.png">
<img width="642" alt="touchbar" src="https://user-images.githubusercontent.com/4501687/70378430-4c7eb980-1946-11ea-85ca-5f8bfe3a67fe.png">


I've tested this in the new version and it's working now...
